jobs:
 - job: J1
   pool:
    name: default
   steps:
     - task: PublishPipelineArtifact@0
       inputs:
         artifactName: 'A1.1'
         targetPath: 'artifact1.1'

     - task: PublishPipelineArtifact@0
       inputs:
        artifactName: 'A1.2'
        targetPath: 'artifact1.2'

 - job: J2
   pool:
    name: default
   dependsOn: J1
   steps:
     - download: 'A1.1'
     - powershell: |
         ls $(Pipeline.Workspace)/


         
