jobs:
 - job: J1
   steps:
     - task: PublishPipelineArtifact@0
       inputs:
         artifactName: 'A1.1'
         targetPath: 'artifact1.1'

     - task: PublishPipelineArtifact@0
       inputs:
        artifactName: 'A1.2'
        targetPath: 'artifact1.2'

 - job: J2
   steps:
     - task: PublishPipelineArtifact@0
       inputs:
        artifactName: 'A2'
        targetPath: 'artifact2'

         
